server:
  port: 8080
spring:
  session:
    initialize-schema: always
    table-name: SPRING_SESSION
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/social
    username: postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          timezone: UTC
  path:
    to:
      image: RestService/src/main/resources/pictures/
  auth:
    jwt:
      secure_key: Hello_kEy-For:my_app-ultra-secure-and-ultra-long-secret
      validity-in-milliseconds: 86400000



